name: zone_local
version: 0.1.1
description: Type-safe zone-scoped variables.
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dart-zone_local

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  meta: '^1.1.0'
  pedantic: '^1.7.0'
  test: '^1.6.0'