name: zone_local
version: 0.1.0
description: Zone-scoped values. Can be used an alternative to dependency injection.
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dart-zone_local

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '^1.1.0'

dev_dependencies:
  pedantic: '^1.0.0'
  test: '^1.4.0'