name: zone_local
version: 0.2.0-nullsafety.1
description:
  A simple, type-safe package for declaring static variables (for configuration, etc.) that can
  have zone-scoped values.
homepage: https://github.com/terrier989/zone_local

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

