name: zone_local
version: 0.1.2
description:
  A simple package for defining zone-scoped values. Typically used for configuration objects.
homepage: https://github.com/terrier989/zone_local

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  meta: '^1.1.0'
  pedantic: '^1.9.0'
  test: '^1.8.0'